### ISSUE TITLE
Can't put opaque newtypes in Arrays

### ISSUE THREAD

**Issue by joroKr21** [alexknvl/newtypes#6]
But you can put `translucent` newtypes:
```scala
@translucent type Foo = Int
@opaque type Bar = Int
Array(Foo.Impl(42)) // ok
Array(Bar.Impl(42)) // no ClassTag
```
I couldn't come up with a modification of the encoding that would solve this.
Maybe at least add a row in the comparison table for `Array`s

**Comment by sir-wabbit** [comment]
Just add an `implicit classTag: ClassTag[Bar]` in the companion object.

**Comment by joroKr21** [comment]
A `ClassTag` that points to `java.lang.Integer` or `Int`? Maybe this should be added by the macro annotation.

**Comment by joroKr21** [comment]
In general this doesn't work, e.g.
```scala
  type HK[G[_], A] = G[A]
  @opaque type OpaqueHK[G[_], A] = HK[G, A]
```
